# -*- coding: utf-8 -*-
"""November Graphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnaXDMIyx-em8JruLSEyuw-pifdnCtWS

*Table 01*
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler


data = {
    'Variable': ['INVEST', 'MONO', 'SIZE', 'AGE', 'ROA', 'LEV', 'GROWTH', 'FIX', 'TOP1', 'INHOLDER', 'MANAGER'],
    'Mean': [0.052, 0.038, 18.745, 1.864, 0.029, 0.491, 0.312, 0.246, 0.412, 0.287, 0.162],
    'Std': [0.091, 0.192, 1.184, 0.762, 0.057, 0.218, 0.835, 0.541, 0.174, 0.213, 0.208],
    'Min': [0.000, 0.000, 16.210, 0.000, -0.238, 0.071, -0.042, -0.362, 0.055, 0.000, 0.003],
    'Max': [0.681, 1.000, 22.356, 3.045, 0.185, 0.921, 5.437, 3.962, 0.981, 0.996, 0.994]
}
df = pd.DataFrame(data)


scaler = MinMaxScaler()
scaled_values = scaler.fit_transform(df[['Mean', 'Std', 'Min', 'Max']])
df_scaled = pd.DataFrame(scaled_values, columns=['Mean', 'Std', 'Min', 'Max'])


labels = df['Variable'].values
num_vars = len(labels)
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]

def add_radar(ax, values, label, color):
    values = values.tolist()
    values += values[:1]
    ax.plot(angles, values, color=color, linewidth=2, label=label)
    ax.fill(angles, values, color=color, alpha=0.25)


fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))
fig.patch.set_facecolor('white')
ax.set_facecolor('white')


add_radar(ax, df_scaled['Mean'], 'Mean', '#4B8BBE')
add_radar(ax, df_scaled['Std'], 'Std', '#FFD43B')
add_radar(ax, df_scaled['Min'], 'Min', '#306998')
add_radar(ax, df_scaled['Max'], 'Max', '#FFE873')


ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)
ax.set_thetagrids(np.degrees(angles[:-1]), labels, fontsize=10)
ax.set_rlabel_position(0)
ax.tick_params(colors='black', labelsize=8)
ax.spines['polar'].set_visible(False)
ax.grid(color='#ccc', linestyle='--', linewidth=0.6)
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), frameon=False)


plt.tight_layout()
plt.savefig('D:\Client_Work_Graphs\Graphs\KAD_Descriptive_Stats_WhiteBG.png', dpi=600, bbox_inches='tight', transparent=False)
plt.show()

"""Table **02**"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import os
from matplotlib.colors import TwoSlopeNorm


os.makedirs("Graphs", exist_ok=True)


data = {
    'Variables': ['MONO', 'SIZE', 'AGE', 'ROA', 'LEV', 'GROWTH', 'FIX', 'TOP1', 'INHOLDER', 'MANAGER'],
    'Expected Impact': [-0.010, 0.006, 0.018, -0.020, -0.060, -0.002, -0.001, 0.025, -0.003, -0.001]
}

df = pd.DataFrame(data)
df = df.sort_values('Expected Impact')


sns.set(style="white", context="talk")
plt.figure(figsize=(12, 7), dpi=600)

norm = TwoSlopeNorm(vmin=df['Expected Impact'].min(), vcenter=0, vmax=df['Expected Impact'].max())
colors = plt.cm.PuOr_r(norm(df['Expected Impact']))

sizes = np.abs(df['Expected Impact']) * 12000 + 900

plt.scatter(df['Expected Impact'], df['Variables'], s=sizes, c=colors, alpha=0.95)

for x, y, val in zip(df['Expected Impact'], df['Variables'], df['Expected Impact']):
    text_color = 'white' if abs(val) > 0.01 else 'black'
    plt.text(x, y, f'{val:.3f}',
             ha='center', va='center',
             fontsize=12, fontweight='bold', color=text_color)

plt.axvline(0, color='gray', linestyle='--', linewidth=1)


plt.xlabel("Estimated Coefficient (Impact on Invest)", fontsize=13)
plt.ylabel("Variables", fontsize=13)

sm = plt.cm.ScalarMappable(cmap='PuOr_r', norm=norm)
sm.set_array([])
cbar = plt.colorbar(sm, orientation='vertical', pad=0.02)
cbar.set_label('Impact Direction & Magnitude', fontsize=12)

plt.grid(alpha=0.25)
sns.despine(left=True, bottom=True)
plt.tight_layout()

plt.savefig("D:\Client_Work_Graphs\Graphs\Investment_Impact_Pakistan_Bubble_Final.png",
            dpi=600, bbox_inches='tight', transparent=False)
plt.show()

"""**Table 03**"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

data = {
    'Period': ['Pre_2', 'Pre_1', 'Current', 'Post_1', 'Post_2'],
    'Estimate': [-0.005, -0.008, -0.002, -0.014, -0.010],
    'T_Value_Abs': [1.05, 1.70, 0.20, 3.55, 3.10],
    'Significance': ['Not significant', 'Not significant', 'Not significant', '*** (1%)', '*** (1%)']
}
df = pd.DataFrame(data)

sns.set_style("whitegrid", {'axes.edgecolor': '.8', 'grid.color': '.8'})

COLOR_ESTIMATE = '#007ACC'
COLOR_T_VALUE = '#FFA500'
COLOR_SIGNIFICANT_HIGHLIGHT = '#D3D3D3'


fig, ax1 = plt.subplots(figsize=(14, 8))


bar_width = 0.35
x = np.arange(len(df['Period']))

for i, period in enumerate(df['Period']):
    if df['Significance'][i] != 'Not significant':
        ax1.axvspan(x[i] - 0.5, x[i] + 0.5, color=COLOR_SIGNIFICANT_HIGHLIGHT, alpha=0.3, zorder=0)

rects1 = ax1.bar(x - bar_width/2, df['Estimate'], bar_width, label='Estimate (Monopoly Effect)',
                 color=COLOR_ESTIMATE, edgecolor='white', linewidth=0.8, zorder=2)


def autolabel_estimate(rects):
    for rect in rects:
        height = rect.get_height()
        ax1.annotate(f'{height:.3f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 5 if height > 0 else -10),
                    textcoords="offset points",
                    ha='center', va='bottom' if height > 0 else 'top',
                    fontsize=10, color='darkslategrey', fontweight='bold')

ax2 = ax1.twinx()
rects2 = ax2.bar(x + bar_width/2, df['T_Value_Abs'], bar_width, label='Absolute T-value',
                 color=COLOR_T_VALUE, edgecolor='white', linewidth=0.8, zorder=2)


def autolabel_t_value(rects):
    for rect in rects:
        height = rect.get_height()
        ax2.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 5),
                    textcoords="offset points",
                    ha='center', va='bottom',
                    fontsize=10, color='darkslategrey', fontweight='bold')

autolabel_estimate(rects1)
autolabel_t_value(rects2)



ax1.axhline(0, color='gray', linewidth=0.8, linestyle='-', zorder=1)

ax1.set_xlabel('Period', fontsize=13, labelpad=15, fontweight='bold', color='dimgrey')
ax1.set_ylabel('Estimate (Effect on Investment)', color=COLOR_ESTIMATE, fontsize=13, fontweight='bold', labelpad=10)
ax1.tick_params(axis='y', labelcolor='dimgrey', labelsize=10)
ax1.set_xticks(x)
ax1.set_xticklabels(df['Period'], fontsize=12, fontweight='bold', color='dimgrey')
ax1.set_ylim(min(df['Estimate']) * 1.6, 0.002)

ax2.set_ylabel('Absolute T-value (Statistical Strength)', color=COLOR_T_VALUE, fontsize=13, fontweight='bold', labelpad=10)
ax2.tick_params(axis='y', labelcolor='dimgrey', labelsize=10)
ax2.set_ylim(0, max(df['T_Value_Abs']) * 1.3)
ax1.grid(axis='y', linestyle=':', alpha=0.6, color='grey')
ax1.grid(axis='x', visible=False)

ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)
ax2.spines['top'].set_visible(False)

lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2,
           loc='lower left',
           bbox_to_anchor=(0.5, 1.05),
           fancybox=True, shadow=True, ncol=2,
           fontsize=11, frameon=True, borderpad=1)


plt.figtext(0.12, 0.02, 'Note: Shaded areas denote periods where the Estimate is statistically significant at the 1% level.',
            fontsize=9, color='gray', ha='left')


plt.tight_layout(rect=[0.05, 0.1, 1, 0.96])

"""**Table 04**"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import FancyBboxPatch

data = {
    'Model': ['(1)', '(2)', '(3)', '(4)', '(5)'],
    'Controls': [1, 1, 1, 1, 1],
    'FE': [1, 1, 1, 1, 1],
    'Firm-year FE': [0, 0, 0, 1, 1],
    'Industry-year FE': [0, 0, 0, 0, 1],
    'R² (Accuracy %)': [61, 62, 68, 62, 18]
}

df = pd.DataFrame(data)
df.set_index('Model', inplace=True)


fig, ax = plt.subplots(figsize=(10, 6))
bottom = np.zeros(len(df))


colors = {
    'Controls': '#CC5500',
    'FE': '#DE7D7D',
    'Firm-year FE': '#390F0F',
    'Industry-year FE': '#E5AA70',
    'R² (Accuracy %)': '#9A8C98'
}


for col in ['Controls', 'FE', 'Firm-year FE', 'Industry-year FE']:
    bars = ax.bar(df.index, df[col], bottom=bottom, color=colors[col], edgecolor='white', linewidth=1.3, label=col)


    for bar in bars:
        height = bar.get_height()
        if height > 0:
            ax.text(
                bar.get_x() + bar.get_width()/2,
                bar.get_y() + height/2,
                col.replace("FE","").strip(),
                ha='center', va='center', color='white', fontsize=8, fontweight='bold'
            )
    bottom += df[col]

ax2 = ax.twinx()
ax2.plot(df.index, df['R² (Accuracy %)'], color='#004700', linewidth=3, marker='o', markersize=8, label='R² (Accuracy %)')
ax2.fill_between(df.index, df['R² (Accuracy %)'], color='#004700', alpha=0.1)
ax2.set_ylim(0, 80)
ax2.set_ylabel("Accuracy (%)", fontsize=12, color='#140505')
ax2.tick_params(axis='y', labelcolor='#140505')


ax.set_xlabel("Model", fontsize=12)
ax.set_ylabel("Normalized Values", fontsize=12, color='#140505')
ax.tick_params(axis='x', labelsize=11)
ax.grid(axis='y', linestyle='--', alpha=0.4)


fig.patch.set_facecolor('#f8f9fa')
ax.set_facecolor('#fdfdfd')


lines, labels = ax.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left', frameon=False, fontsize=9)

for patch in ax.patches:
    patch.set_path_effects([])

plt.tight_layout()
plt.show()

"""**Table 05**"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn

labels = [
    "Monopoly → Slack (Reserves)",
    "Monopoly → Investment",
    "Slack → Investment",
    "Monopoly → Debt",
    "Debt → Investment",
    "Monopoly → Equity",
    "Equity → Investment"
]


R2 = [96, 61, 61, 3, 77, 48, 17]
coef = [0.014, -0.009, -0.018, 0.300, 0.002, -0.016, 0.015]
tvalue = [5.40, -3.80, -2.95, 1.75, 2.40, -4.25, 3.50]

def normalize(values):
    vmin, vmax = min(values), max(values)
    return [100 * (v - vmin) / (vmax - vmin) for v in values]

coef_norm = normalize(coef)
t_norm = normalize(tvalue)

angles = np.linspace(0, 2 * np.pi, len(labels), endpoint=False).tolist()
angles += angles[:1]
R2 += R2[:1]
coef_norm += coef_norm[:1]
t_norm += t_norm[:1]

fig, ax = plt.subplots(figsize=(9, 9), subplot_kw=dict(polar=True))

ax.plot(angles, R2, color='#1f77b4', linewidth=2.2, marker='o', label='R² Accuracy (%)')
ax.plot(angles, coef_norm, color='#d62728', linewidth=2.2, marker='s', label='Coefficient (normalized)')
ax.plot(angles, t_norm, color='#2ca02c', linewidth=2.2, marker='^', label='t-value (normalized)')

ax.fill(angles, R2, color='#1f77b4', alpha=0.10)
ax.fill(angles, coef_norm, color='#d62728', alpha=0.10)
ax.fill(angles, t_norm, color='#2ca02c', alpha=0.10)

ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)
ax.set_thetagrids(np.degrees(angles[:-1]), labels, fontsize=10, fontweight='medium', color='black')
ax.set_rlabel_position(0)
ax.tick_params(colors='black', labelsize=8)
ax.spines['polar'].set_visible(False)
ax.grid(color='#ccc', linestyle='--', linewidth=0.6)

ax.set_ylim(0, 100)
ax.set_yticks([20, 40, 60, 80, 100])
ax.set_yticklabels(["20", "40", "60", "80", "100"], fontsize=8, color='gray')


ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), frameon=False, fontsize=9)

plt.tight_layout()
plt.show()

"""Table 06"""

import matplotlib.pyplot as plt
import numpy as np

industries = ["High Capital Intensity", "Low Capital Intensity"]
investment_effect = [0.7, 0.9]
accuracy = [67, 61]
t_value = [2.0, 3.5]

color_invest = "#F1C40F"   # yellow
color_accuracy = "#1ABC9C" # teal
color_tval = "#34495E"     # dark gray
color_line = "#2980B9"     # blue

plt.style.use("default")
fig, ax1 = plt.subplots(figsize=(10, 6), dpi=140)
fig.patch.set_facecolor("#f7f7f7")

x = np.arange(len(industries))
bar_width = 0.25

bars1 = ax1.bar(x - bar_width, [i * 100 for i in investment_effect],
                width=bar_width, color=color_invest, alpha=0.9,
                label="Investment Reduction (%)", zorder=3)
bars2 = ax1.bar(x, accuracy, width=bar_width,
                color=color_accuracy, alpha=0.9,
                label="R² Accuracy (%)", zorder=3)
bars3 = ax1.bar(x + bar_width, [t * 10 for t in t_value],
                width=bar_width, color=color_tval, alpha=0.95,
                label="t-Value (scaled)", zorder=3)

ax2 = ax1.twinx()
x_smooth = np.linspace(x[0], x[-1], 200)
y_smooth = np.interp(x_smooth, x, accuracy)

ax2.plot(x_smooth, y_smooth, color="white", linewidth=6, alpha=0.6, zorder=4)

ax2.plot(x_smooth, y_smooth, color=color_line, linewidth=2.8,
         linestyle="--", dash_capstyle='round', zorder=5,
         label="Accuracy Trend")

ax2.scatter(x, accuracy,
            s=160,
            facecolors="white",
            edgecolors=color_line,
            linewidths=2.5,
            zorder=6)
ax2.scatter(x, accuracy,
            s=50,
            color=color_line,
            zorder=7,
            alpha=0.9)

for bars in [bars1, bars2, bars3]:
    for bar in bars:
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2,
                 height + 3,
                 f"{height:.0f}",
                 ha="center", va="bottom",
                 fontsize=10, color="#2c3e50",
                 fontweight="bold", zorder=8)

ax1.set_xticks(x)
ax1.set_xticklabels(industries, fontsize=11, fontweight="bold", rotation=10)
ax1.set_ylabel("Values (Scaled)", fontsize=12, fontweight="bold", color="#2c3e50")
ax2.set_ylabel("Accuracy (%)", fontsize=12, fontweight="bold", color=color_line)

ax1.set_ylim(0, 110)
ax2.set_ylim(50, 100)

handles1, labels1 = ax1.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(handles1 + handles2, labels1 + labels2,
           loc="upper left", bbox_to_anchor=(0.5, 1.15),
           ncol=2, frameon=True, fontsize=8,
           facecolor="white", edgecolor="#dddddd",
           fancybox=True, framealpha=0.95)

# --- Grid & cleanup ---
ax1.grid(axis="y", linestyle="--", alpha=0.35, zorder=1)
for spine in ax1.spines.values():
    spine.set_visible(False)
for spine in ax2.spines.values():
    spine.set_visible(False)

plt.tight_layout(rect=[0, 0, 1, 0.92])
plt.show()

"""Table 07"""

import matplotlib.pyplot as plt
import numpy as np

regions = [
    "Higher Marketization (Punjab & Sindh)",
    "Lower Marketization (KP & Balochistan)"
]

investment_reduction = [0.9, 0.2]
accuracy = [61, 68]

sorted_indices = np.argsort(investment_reduction)[::-1]
regions = [regions[i] for i in sorted_indices]
investment_reduction = [investment_reduction[i] for i in sorted_indices]
accuracy = [accuracy[i] for i in sorted_indices]

cumulative = np.cumsum(accuracy) / sum(accuracy) * 100

plt.style.use("default")
fig, ax1 = plt.subplots(figsize=(10, 5), dpi=140)
fig.patch.set_facecolor("white")

bars = ax1.barh(
    regions,
    investment_reduction,
    color="#000075",
    edgecolor="white",
    label="Investment Reduction (%)",
    height=0.5
)

ax2 = ax1.twiny()
ax2.plot(
    cumulative,
    regions,
    color="#7393B3",
    marker="o",
    markersize=5,
    linewidth=2.0,
    label="Cumulative (%)"
)
ax2.fill_betweenx(regions, cumulative, color="#7393B3", alpha=0.25)

for i, bar in enumerate(bars):
    width = bar.get_width()
    ax1.text(width + 0.05, bar.get_y() + bar.get_height()/2,
             f"{width:.1f}%", va='center', ha='left',
             color="#FF5533", fontsize=11, fontweight='bold')

for i, val in enumerate(cumulative):
    ax2.text(val + 0.5, regions[i], f"{val:.1f}%", va='center',
             ha='left', color="#FF5533", fontsize=10, fontweight="bold")

ax1.set_xlabel("Investment Reduction (%)", fontsize=12, fontweight="bold", color="#000000")
ax2.set_xlabel("Cumulative (%)", fontsize=12, fontweight="bold", color="#000000")

ax1.grid(axis="x", linestyle="--", alpha=0.4)
ax1.set_facecolor("#FAFAFA")
ax1.spines["right"].set_visible(False)
ax1.spines["top"].set_visible(False)
ax2.spines["top"].set_visible(False)
ax2.spines["bottom"].set_visible(False)
ax1.invert_yaxis()

lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
plt.legend(lines + lines2, labels + labels2,
           loc="upper left", bbox_to_anchor=(0.5, 1.25),
           ncol=2, frameon=True, fontsize=8,
           facecolor="white", edgecolor="#dddddd",
           fancybox=True, framealpha=0.95)

plt.tight_layout()
plt.show()